/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.33
 * Generated at: 2024-12-13 10:24:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.jobmarket.hired.model.Country;
import com.jobmarket.hired.model.Job_salary;
import com.jobmarket.hired.model.Job_contract;
import java.util.ArrayList;
import com.jobmarket.hired.model.Job_category;
import java.util.List;
import com.jobmarket.company.model.Applied_job;
import java.util.List;
import com.jobmarket.Session_constants;

public final class company_005fjob_005fposting_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/includes/company_homepage_header.jsp", Long.valueOf(1732806874126L));
    _jspx_dependants.put("/includes/index_footer.jsp", Long.valueOf(1723760577040L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(11);
    _jspx_imports_classes.add("com.jobmarket.company.model.Applied_job");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.jobmarket.Session_constants");
    _jspx_imports_classes.add("com.jobmarket.hired.model.Job_contract");
    _jspx_imports_classes.add("com.jobmarket.hired.model.Job_salary");
    _jspx_imports_classes.add("com.jobmarket.hired.model.Country");
    _jspx_imports_classes.add("com.jobmarket.hired.model.Job_category");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    ");

//     		session = request.getSession(false);
    
        //THIS ATTRIBUTES ARE SENT FROM "com.jobmarket.hired.controller/Display_work_category.java" .
                            	//Its function is to display the drop down box with predetermined values.
                         			   
                            	List<Job_category> job_category_list = new ArrayList<Job_category>();
                            	if(request.getAttribute("attr_job_category_list")!=null){
                            		job_category_list = (List<Job_category>) request.getAttribute("attr_job_category_list");
                            	}
                            	List<Country> job_country_list = new ArrayList<Country>();
                            	if(request.getAttribute("attr_job_country_list")!=null){
                            		job_country_list = (List<Country>) request.getAttribute("attr_job_country_list");
                            	}
                            	List<Job_contract> job_contract_list = new ArrayList<Job_contract>();
                            	if(request.getAttribute("attr_job_contract_list")!=null){
                            		job_contract_list = (List<Job_contract>) request.getAttribute("attr_job_contract_list");
                            	}
                            	List<Job_salary> job_salary_list = new ArrayList<Job_salary>();
                            	if(request.getAttribute("attr_job_salary_list")!=null){
                            		job_salary_list = (List<Job_salary>) request.getAttribute("attr_job_salary_list");
                            	}
                            	
        
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Post your job</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"styles/index_header.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"styles/job_posting_style.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("		\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    ");

    		String session_name = (String) session.getAttribute("attr_company_email");
    
    
    session = request.getSession(false);
 	Integer session_company_id = (Integer) session.getAttribute( Session_constants.COMPANY_SESSION_ID );
 	String session_company_name = (String) session.getAttribute( Session_constants.COMPANY_SESSION_NAME );
 	String session_company_email = (String) session.getAttribute(Session_constants.COMPANY_SESSION_EMAIL);
 	String session_company_password = (String) session.getAttribute(Session_constants.COMPANY_SESSION_PASSWORD);
 	String session_company_telephone = (String) session.getAttribute(Session_constants.COMPANY_SESSION_TELEPHONE);
 	String session_company_address = (String) session.getAttribute(Session_constants.COMPANY_SESSION_ADDRESS);
 	String session_company_country = (String) session.getAttribute(Session_constants.EMPLOYEE_SESSION_COUNTRY);
 	int session_company_country_id = (Integer) session.getAttribute(Session_constants.COMPANY_SESSION_COUNTRY_ID);
 	String session_company_city = (String) session.getAttribute(Session_constants.COMPANY_SESSION_CITY);

    
 	List<Applied_job> applied_job_info = (List<Applied_job>) session.getAttribute(Session_constants.COMPANY_SESSION_APPLIED_JOB);
 	
 	
 	
 	
    
    
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"styles/index_header.css\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("		<header>	\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("					<h1>HIRED & HIRE</h1>\r\n");
      out.write("			\r\n");
      out.write("	\r\n");
      out.write("		</header>\r\n");
      out.write("	\r\n");
      out.write("	<nav>\r\n");
      out.write("		<ul>\r\n");
      out.write("				<li><a href=\"Display_company_posted_job\">Home</a></li>\r\n");
      out.write("				<li><a href=\"Company_start_job_posting\">Post Job</a></li>\r\n");
      out.write("				<li><a href=\"Display_job_applicant\">Applicants</a></li>\r\n");
      out.write("<!-- 				<li><a href=\"company_message.jsp\">Messages</a></li> -->\r\n");
      out.write("				<li class=\"float_right\"><a href=\"To_company_profile\">My Account</a></li>		\r\n");
      out.write("<!-- 				<li class=\"float_right\"><a href=\"/src/main/webapp/company_profile\">My Account</a></li>		 -->\r\n");
      out.write("	\r\n");
      out.write("				<li class=\"float_right\"><a href=\"Company_log_out\">Log out : ");
      out.print(session_name  );
      out.write("</a></li>\r\n");
      out.write("			\r\n");
      out.write("		</ul>\r\n");
      out.write("	</nav>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("	\r\n");
      out.write("		\r\n");
      out.write("	<main>\r\n");
      out.write("		<section class=\"form_section\">\r\n");
      out.write("	\r\n");
      out.write("				<form method=\"POST\" action=\"Job_posting\">\r\n");
      out.write("				\r\n");
      out.write("				\r\n");
      out.write("					<article class=\"company_id\">\r\n");
      out.write("					<label for=\"company_id\">COMPANY ID </label>\r\n");
      out.write("					<input type=\"text\" name=\"company_id\" value=\"");
      out.print(session.getAttribute("attr_company_id"));
      out.write("\" readonly=\"readonly\" >\r\n");
      out.write("					\r\n");
      out.write("					</article>\r\n");
      out.write("					\r\n");
      out.write("					<article class=\"country_id\">\r\n");
      out.write("					<label for=\"country_id\">COUNTRY ID </label>\r\n");
      out.write("					<input type=\"text\" name=\"country_id\" value=\"");
      out.print(session.getAttribute("attr_company_country_id"));
      out.write("\" readonly=\"readonly\" >\r\n");
      out.write("					\r\n");
      out.write("					</article>\r\n");
      out.write("				\r\n");
      out.write("				<!-- change value of select to id from name -->\r\n");
      out.write("					<article class=\"job_category\">\r\n");
      out.write("							<label for=\"job_category\">JOB CATEGORY </label><br>\r\n");
      out.write("							<select  name=\"job_category\" id=\"job_category\">\r\n");
      out.write("							");

							for(Job_category element : job_category_list){
							
      out.write("\r\n");
      out.write("								<option value=\"");
      out.print(element.getCategory_id());
      out.write('"');
      out.write('>');
      out.write(' ');
      out.print(element.getCategory_name());
      out.write("</option>\r\n");
      out.write("								");

								}
								
      out.write("\r\n");
      out.write("							</select>	\r\n");
      out.write("					</article>\r\n");
      out.write("					\r\n");
      out.write("					\r\n");
      out.write("					<article class=\"job_name\">\r\n");
      out.write("						<label for=\"job_name\">JOB NAME </label><br>\r\n");
      out.write("						<input type = \"text\" name=\"job_name\" id=\"job_name\" placeholder=\"Job Name\">\r\n");
      out.write("					</article>\r\n");
      out.write("					<br><br>\r\n");
      out.write("					\r\n");
      out.write("					<article class=\"job_vacancy\">\r\n");
      out.write("						<label for=\"job_vacancy\">JOB VACANCY </label><br>\r\n");
      out.write("						<input type = \"number\" min=\"0\" max=\"100\" name=\"job_vacancy\" id=\"job_vacancy\" placeholder=\"Job Vacancy\">\r\n");
      out.write("					</article>\r\n");
      out.write("					<br><br>\r\n");
      out.write("					\r\n");
      out.write("\r\n");
      out.write("					\r\n");
      out.write("					<article class=\"job_descripcion\">\r\n");
      out.write("						<label for=\"job_descripcion\">JOB DESCRIPTION </label><br>\r\n");
      out.write("						<textarea  name=\"job_descripcion\" id=\"job_descripcion\" placeholder=\"Job Description\" ></textarea>\r\n");
      out.write("					</article>\r\n");
      out.write("					<br><br>\r\n");
      out.write("					\r\n");
      out.write("					<article class=\"job_address\">\r\n");
      out.write("						<label for=\"job_address\">JOB ADDRESS </label><br>\r\n");
      out.write("						<input type = \"text\" name=\"job_address\" id=\"job_address\" placeholder=\"Job Address\">\r\n");
      out.write("					</article>\r\n");
      out.write("					<br><br>	\r\n");
      out.write("					\r\n");
      out.write("					<article class=\"job_city\">\r\n");
      out.write("						<label for=\"job_city\">JOB CITY</label><br>\r\n");
      out.write("						<input type = \"text\" name=\"job_city\" id=\"job_city\" placeholder=\"Job City\" >\r\n");
      out.write("					</article>\r\n");
      out.write("					<br><br>\r\n");
      out.write("					\r\n");
      out.write("					\r\n");
      out.write("\r\n");
      out.write("					\r\n");
      out.write("					\r\n");
      out.write("					<article class=\"job_contract\">\r\n");
      out.write("						<label for=\"job_contract\">JOB CONTRACT TYPE </label><br>\r\n");
      out.write("						<select  name=\"job_contract\" id=\"job_contract\">\r\n");
      out.write("							");

							for(Job_contract element : job_contract_list){
							
      out.write("\r\n");
      out.write("								<option value=\"");
      out.print(element.getContract_id());
      out.write('"');
      out.write('>');
      out.write(' ');
      out.print(element.getContract_name());
      out.write("</option>\r\n");
      out.write("								");

								}
								
      out.write("\r\n");
      out.write("						</select>	\r\n");
      out.write("					</article>\r\n");
      out.write("					<br>\r\n");
      out.write("					\r\n");
      out.write("					\r\n");
      out.write("					<article class=\"job_salary\">\r\n");
      out.write("						<label for=\"job_salary\"> BRUTE ANUAL SALARY </label><br>\r\n");
      out.write("						<select  name=\"job_salary\" id=\"job_salary\">\r\n");
      out.write("								");

								for(Job_salary element : job_salary_list){
								
      out.write("\r\n");
      out.write("								<option value=\"");
      out.print(element.getSalary_id() );
      out.write('"');
      out.write('>');
      out.write(' ');
      out.print(element.getSalary_amount());
      out.write("</option>\r\n");
      out.write("								");
} 
      out.write("\r\n");
      out.write("						</select>	\r\n");
      out.write("					</article>\r\n");
      out.write("					<br>\r\n");
      out.write("					\r\n");
      out.write("				\r\n");
      out.write("					\r\n");
      out.write("					\r\n");
      out.write("					<article class=\"buttons\">\r\n");
      out.write("						<input type=\"reset\" id=\"reset\" name= \"reset\" value=\"Reset\">\r\n");
      out.write("						<input type=\"submit\" id=\"submit\" name=\"submit\" value=\"Post\">\r\n");
      out.write("					</article><br><br>\r\n");
      out.write("					\r\n");
      out.write("				\r\n");
      out.write("				\r\n");
      out.write("				</form>\r\n");
      out.write("	\r\n");
      out.write("		</section>\r\n");
      out.write("	</main>\r\n");
      out.write("	\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("		\r\n");
      out.write("	<footer>\r\n");
      out.write("			\r\n");
      out.write("			<div class=\"footer_left\">\r\n");
      out.write("					\r\n");
      out.write("					<ul>\r\n");
      out.write("						<li><a href=\"#\">About Hired</a></li>\r\n");
      out.write("						<li><a href=\"#\">Our Motive</a></li>\r\n");
      out.write("						<li><a href=\"#\">Work with us</a></li>\r\n");
      out.write("						\r\n");
      out.write("					</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("			<div class=\"footer_center\">\r\n");
      out.write("					\r\n");
      out.write("					<ul>\r\n");
      out.write("						\r\n");
      out.write("						<li><a href=\"#\">Legal Conditions</a></li>\r\n");
      out.write("						<li><a href=\"#\">Privacy Policy</a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("			<div class=\"footer_right\">\r\n");
      out.write("					\r\n");
      out.write("					<ul>\r\n");
      out.write("						<li><a href=\"#\">Use of Services</a></li>\r\n");
      out.write("						<li><a href=\"#\">Manage Cookies</a></li>\r\n");
      out.write("						\r\n");
      out.write("					</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("	</footer>\r\n");
      out.write("	\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("		\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
