/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.33
 * Generated at: 2024-12-13 10:21:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.ArrayList;
import com.jobmarket.hired.model.Country;
import java.util.List;
import com.jobmarket.company.model.Job_wrapper;
import java.util.ArrayList;
import com.jobmarket.hired.model.Country;
import java.util.List;

public final class company_005fsign_005fup_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/includes/index_header.jsp", Long.valueOf(1729161645166L));
    _jspx_dependants.put("/includes/index_footer.jsp", Long.valueOf(1723760577040L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(6);
    _jspx_imports_classes.add("com.jobmarket.company.model.Job_wrapper");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.jobmarket.hired.model.Country");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    ");

    	//FROM Sign_up_company. repeat password wrong
    	String password_error = (String) request.getAttribute("attr_password_error");
    
		    
  //FROM hired_controller/Display_country.
	List<Country> country_list = new ArrayList<Country>();
	if(request.getAttribute("attr_country_list")!=null){
		country_list = (List<Country>) request.getAttribute("attr_country_list"); 
	}
    
    
    
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Sign up - Company</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"styles/index_header.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"styles/sign_up_company_style.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("   \r\n");
      out.write("    \r\n");
      out.write("     ");

		//THIS PART IS SO THAT YOU CAN SEE THE JOBS WITHOUT LOGGING IN:
			
				//ALL JOBS TO DISPLAY ON HOMEPAGE From "Employee_homepage" Servlet.
				List<Job_wrapper> job_list = new ArrayList<Job_wrapper>();
				if(request.getAttribute("attr_job_list")!=null){
					job_list = (List<Job_wrapper>) request.getAttribute("attr_job_list");
				}
				
				//List of saved job from "DISPLAY_SAVED_JOB"  servlet.
				List<Job_wrapper> saved_job_list = new ArrayList<Job_wrapper>();
				if(request.getAttribute("attr_saved_job_list")!=null){
					saved_job_list = (List<Job_wrapper>) request.getAttribute("attr_saved_job_list");
				}
				
				
				//this is the list of country to show in employee account settings.
				List<Country> country_list1 = new ArrayList<Country>();
				if(request.getAttribute("attr_country_list")!=null){
					country_list1 = (List<Country>) request.getAttribute("attr_country_list");
				}
				
				
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<header>	\r\n");
      out.write("		\r\n");
      out.write("\r\n");
      out.write("					<h1>HIRED & HIRE</h1>\r\n");
      out.write("		\r\n");
      out.write("	\r\n");
      out.write("	</header>\r\n");
      out.write("	\r\n");
      out.write("	<nav>\r\n");
      out.write("		<ul>\r\n");
      out.write("			<li><a href=\"index.jsp\"> Home </a></li>\r\n");
      out.write("<!-- 			<li><a href=\"#\"> Search companies </a></li> -->\r\n");
      out.write("			<li><a href=\"Index_jobs\"> Search Jobs </a></li>\r\n");
      out.write("			<li><a href=\"about_us.jsp\"> About us </a></li>\r\n");
      out.write("		</ul>\r\n");
      out.write("	</nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<main>\r\n");
      out.write("			<section class=\"form_outer_area\">\r\n");
      out.write("				<form class=\"form_area\" method=\"POST\" action=\"Sign_up_company_insert\">\r\n");
      out.write("					\r\n");
      out.write("						<article class=\"form_left\">\r\n");
      out.write("								<label for=\"company_name\">Company Name </label>\r\n");
      out.write("								<input type=\"text\" name=\"company_name\" id=\"company_name\" placeholder=\"Company name\"><br><br><br>\r\n");
      out.write("								\r\n");
      out.write("								<label for=\"company_telephone\">Telephone  </label>\r\n");
      out.write("								<input type=\"text\" name=\"company_telephone\" id=\"company_telephone\" placeholder=\"Company telephone\"><br><br><br>\r\n");
      out.write("								\r\n");
      out.write("								<label for=\"company_email\">Company Email </label>\r\n");
      out.write("								<input type=\"email\" name=\"company_email\" id=\"company_email\" placeholder=\"Company email\"><br><br><br>\r\n");
      out.write("							\r\n");
      out.write("								\r\n");
      out.write("								<label for=\"country\">Country </label>\r\n");
      out.write("								<select name=\"country\" id=\"country\">\r\n");
      out.write("									");
for(Country element : country_list){ 
      out.write("\r\n");
      out.write("										<option value=\"");
      out.print(element.getId());
      out.write('"');
      out.write('>');
      out.write(' ');
      out.print(element.getCountry_name() );
      out.write(" </option>\r\n");
      out.write("									");
} 
      out.write("\r\n");
      out.write("								</select>\r\n");
      out.write("								<br><br><br>\r\n");
      out.write("								\r\n");
      out.write("								<label for=\"city_name\">City Name </label>\r\n");
      out.write("								<input type=\"text\" name=\"city_name\" id=\"city_name\" placeholder=\"City name\"><br><br><br>\r\n");
      out.write("								\r\n");
      out.write("								<label for=\"address\">Address </label>\r\n");
      out.write("								<input type=\"text\" name=\"address\" id=\"address\" placeholder=\"Address\"><br><br><br>\r\n");
      out.write("								\r\n");
      out.write("								<label for=\"company_password\">Your Password </label>\r\n");
      out.write("								<input type=\"password\" name=\"company_password\" id=\"company_password\" placeholder=\"Password\"><br><br><br>\r\n");
      out.write("								\r\n");
      out.write("								<label for=\"company_password_repeat\">Repeat Your Password </label>\r\n");
      out.write("								<input type=\"password\" name=\"company_password_repeat\" id=\"company_password_repeat\" placeholder=\"Password\"><br><br><br>\r\n");
      out.write("								\r\n");
      out.write("								\r\n");
      out.write("								\r\n");
      out.write("								<input type =\"reset\" name=\"reset\" id=\"reset\" value=\"Reset\">\r\n");
      out.write("								<input type=\"submit\" name=\"sign_up_company\" id=\"sign_up_company\" value=\"Sign up\">\r\n");
      out.write("						</article>\r\n");
      out.write("					\r\n");
      out.write("					\r\n");
      out.write("					\r\n");
      out.write("					\r\n");
      out.write("						<article class=\"form_right\">\r\n");
      out.write("								\r\n");
      out.write("								\r\n");
      out.write("								\r\n");
      out.write("								\r\n");
      out.write("									\r\n");
      out.write("												");
if(password_error!=null){ 
      out.write("\r\n");
      out.write("														<div class=\"password_error\">\r\n");
      out.write("														\r\n");
      out.write("															<p>");
      out.print(password_error );
      out.write("</p>\r\n");
      out.write("														</div>\r\n");
      out.write("												");
} 
      out.write("	\r\n");
      out.write("									\r\n");
      out.write("									\r\n");
      out.write("						</article>\r\n");
      out.write("						\r\n");
      out.write("						\r\n");
      out.write("				</form>\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("			</section>\r\n");
      out.write("	</main>\r\n");
      out.write("\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("		\r\n");
      out.write("	<footer>\r\n");
      out.write("			\r\n");
      out.write("			<div class=\"footer_left\">\r\n");
      out.write("					\r\n");
      out.write("					<ul>\r\n");
      out.write("						<li><a href=\"#\">About Hired</a></li>\r\n");
      out.write("						<li><a href=\"#\">Our Motive</a></li>\r\n");
      out.write("						<li><a href=\"#\">Work with us</a></li>\r\n");
      out.write("						\r\n");
      out.write("					</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("			<div class=\"footer_center\">\r\n");
      out.write("					\r\n");
      out.write("					<ul>\r\n");
      out.write("						\r\n");
      out.write("						<li><a href=\"#\">Legal Conditions</a></li>\r\n");
      out.write("						<li><a href=\"#\">Privacy Policy</a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("			<div class=\"footer_right\">\r\n");
      out.write("					\r\n");
      out.write("					<ul>\r\n");
      out.write("						<li><a href=\"#\">Use of Services</a></li>\r\n");
      out.write("						<li><a href=\"#\">Manage Cookies</a></li>\r\n");
      out.write("						\r\n");
      out.write("					</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("	</footer>\r\n");
      out.write("	\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("		\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
